steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA",
        "-f",
        "Dockerfile",
        ".",
      ]
  # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "services"
      - "update-traffic"
      - "${_SERVICE_NAME}"
      - "--to-revisions"
      - "LATEST=100"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
substitutions:
  _SERVICE_NAME: pay-smobil # default value. Don't leave empty! right
images:
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY